# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  styles: source/_data/next.styles.styl

# ---------------------------------------------------------------
# Site Information Settings
# See: https://theme-next.org/docs/getting-started/
# ---------------------------------------------------------------
favicon:
  small: https://blog.jiapan.tw/assets/favicon/favicon-16x16.png
  medium: https://blog.jiapan.tw/assets/favicon/favicon-32x32.png
  apple_touch_icon: https://blog.jiapan.tw/assets/favicon/apple-icon-57x57.png
  # safari_pinned_tab: /images/logo.svg
  android_manifest: https://blog.jiapan.tw/assets/favicon/manifest.json
  ms_browserconfig: https://blog.jiapan.tw/assets/favicon/browserconfig.xml

footer:
  since: 2018
  icon:
    name: heart
    animated: true
    color: "#808080"
  copyright: Justin Tien
  # -------------------------------------------------------------
  powered:
    enable: true
    version: true
  theme:
    enable: true
    version: true
  custom_text: Theme source code <span class="exturl theme-link" data-url="aHR0cHM6Ly9naXRodWIuY29tL3RoZW1lLW5leHQvaGV4by10aGVtZS1uZXh0">here</span><br>Website source code <span class="exturl theme-link" data-url="aHR0cHM6Ly9naXRodWIuY29tL3RoZW1lLW5leHQvdGhlbWUtbmV4dC5vcmc=">here</span>

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
#scheme: Mist # 簡約單列
#scheme: Muse # 寬屏經典布局
#scheme: Pisces # 雙欄布局，適合技術筆記。
scheme: Gemini # 結合雙欄與現代風格，建議使用
darkmode: true

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# ---------------------------------------------------------------
# Sidebar Settings
# See: https://theme-next.org/docs/theme-settings/sidebar
# ---------------------------------------------------------------
sidebar:
  onmobile: true

# Sidebar Avatar
avatar:
  # In theme directory (source/images): /images/avatar.gif
  # In site directory (source/uploads): /uploads/avatar.gif
  # You can also use other linking images.
  url: https://blog.jiapan.tw/assets/logo.png #/images/avatar.gif
  # If true, the avatar would be dispalyed in circle.
  rounded: false
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1
  # If true, the avatar would be rotated with the cursor.
  rotated: false

social:
  GitHub: https://github.com/justintien || fab fa-github
  E-Mail: mailto:thitbbeb+justintien.jiapan.tw@gmail.com || fa fa-envelope
  #Weibo: https://weibo.com/yourname || weibo
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

social_icons:
  enable: true
  icons_only: false
  transition: false

links:
  賈胖技術部落格: http://blog.jiapan.tw

toc:
  enable: true
  number: true
  wrap: true

# ---------------------------------------------------------------
# Post Settings
# See: https://theme-next.org/docs/theme-settings/posts
# ---------------------------------------------------------------

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true
  awl: 4
  wpm: 275

follow_me:
  Telegram [Chat]: https://t.me/joinchat/IYNXoxaIXHpMcEe-R8AC5g || fab fa-telegram
  Telegram [News]: https://t.me/joinchat/AAAAAFg7qgTluqXNbotdxw || fab fa-telegram
  RSS: /atom.xml || fa fa-rss

post_edit:
  enable: true
  url: https://github.com/justintien/justintien.github.io/edit/hexo/source/

# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------
mobile_layout_economy: true
back2top:
  enable: true
  sidebar: true
  scrollpercent: true

# ---------------------------------------------------------------
# Font Settings
# See: https://theme-next.org/docs/theme-settings/#Fonts-Customization
# ---------------------------------------------------------------
# Find fonts on Google Fonts (https://www.google.com/fonts)
# All fonts set here will have the following styles:
#   light | light italic | normal | normal italic | bold | bold italic
# Be aware that setting too much fonts will cause site running slowly
# ---------------------------------------------------------------
# To avoid space between header and sidebar in scheme Pisces / Gemini, Web Safe fonts are recommended for `global` (and `title`):
# Arial | Tahoma | Helvetica | Times New Roman | Courier New | Verdana | Georgia | Palatino | Garamond | Comic Sans MS | Trebuchet MS
# ---------------------------------------------------------------

font:
  enable: true

  # Uri of fonts host, e.g. https://fonts.googleapis.com (Default).
  host:

  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: "Roboto, sans-serif" # 全球默認字體
    size:

  # Font settings for site title (.site-title).
  title:
    external: true
    family:
    size:

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: "Montserrat, sans-serif" # 標題字體
    size:

  # Font settings for posts (.post-body).
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family:

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------
index_with_subtitle: true
exturl: true

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: false

github_banner:
  enable: true
  permalink: https://github.com/justintien/justintien.github.io
  title: Fork on GitHub

# ---------------------------------------------------------------
# Comments Settings
# See: https://theme-next.org/docs/third-party-services/comments
# ---------------------------------------------------------------

# Disqus
disqus:
  enable: true
  shortname: justintien
  count: true
  #post_meta_order: 0

# ---------------------------------------------------------------
# Tags Settings
# See: https://theme-next.org/docs/tag-plugins/
# ---------------------------------------------------------------

note:
  style: simple
  icons: true
  border_radius: 0
  light_bg_offset: -3

tabs:
  enable: true
  transition:
    tabs: true
    labels: true
  border_radius: 0

# ---------------------------------------------------------------
# Search Services
# See: https://theme-next.org/docs/third-party-services/search-services
# ---------------------------------------------------------------

# Google Analytics
google_analytics:
  tracking_id: UA-59277879-1
  only_pageview: false

# ---------------------------------------------------------------
# Search Services
# See: https://theme-next.org/docs/third-party-services/search-services
# ---------------------------------------------------------------
local_search:
  enable: true
  trigger: auto
